url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/website" # the subpath of your site, e.g. /blog
title: "Charlie Homewood" # the name of your site, e.g. ACME Corp.
include: ['_pages'] # includes the _pages subfolder, allowing pages in that folder to be loaded.
author: Charlie Homewood

collections:
  projects:
    output: true
    permalink: /projects/:path/